steps:
- name: gcr.io/kaniko-project/executor:latest
  args: ["--dockerfile=./Dockerfile",
         "--destination=gcr.io/turnkey-cyclist-245521/hello-world-nginx:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/hello-world-nginx-deployment', 'hello-world-nginx=gcr.io/turnkey-cyclist-245521/hello-world-nginx:$REVISION_ID', '-n', 'hwnginx']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster3'

