apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
  labels:
    app: hello-world-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-nginx
  template:
    metadata:
      labels:
        app: hello-world-nginx
    spec:
      containers:
        - name: hello-world-nginx
          image: gcr.io/turnkey-cyclist-245521/hello-world-nginx:latest