apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx-deployment
  labels:
    app: hello-world-nginx
spec:
  replicas: 3
  selector:
    matchlables:
      app: hello-world-nginx
  template:
    metadata:
      labels:
        app: hello-world-nginx
    spec:
      containers:
      - name: hello-world-nginx
        image: gcr.io/$GOOGLE_CLOUD_PROJECT/hello-world-nginx:latest