apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: gcr.io/turnkey-cyclist-245521/hello-world-nginx
  googleCloudBuild:
    projectId: turnkey-cyclist-245521
deploy:
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/thescott/k8s-nginx/main/hello-world-nginx-deploy.yaml
